return {
    name = "Z Fighter's Anthem",
    audio = "assets/Z Fighter's Anthem.mp3",
    difficulty = "Custom",
    bpm = 120,
    arrows = {
        {time = 0.53, direction = "left"},
        {time = 0.83, direction = "right"},
        {time = 1.12, direction = "left"},
        {time = 1.41, direction = "right"},
        {time = 1.77, direction = "up"},
        {time = 2.08, direction = "down"},
        {time = 2.45, direction = "left"},
        {time = 2.79, direction = "right"},
        {time = 3.12, direction = "left"},
        {time = 3.42, direction = "right"},
        {time = 3.73, direction = "left"},
        {time = 4.04, direction = "right"},
        {time = 4.37, direction = "left"},
        {time = 4.66, direction = "right"},
        {time = 4.98, direction = "left"},
        {time = 5.33, direction = "right"},
        {time = 5.66, direction = "left"},
        {time = 5.99, direction = "right"},
        {time = 6.32, direction = "left"},
        {time = 6.63, direction = "right"},
        {time = 6.95, direction = "left"},
        {time = 7.25, direction = "right"},
        {time = 7.56, direction = "left"},
        {time = 7.88, direction = "right"},

        -- 8-16 seconds
        -- Intense Pattern
        {time = 8.22, direction = "left"},
        {time = 8.56, direction = "right"},
        {time = 8.90, direction = "left"},
        {time = 9.20, direction = "right"},
        {time = 9.58, direction = "left"},
        {time = 9.86, direction = "right"},
        {time = 10.19, direction = "left"},
        {time = 10.52, direction = "right"},
        {time = 10.87, direction = "right"},
        {time = 11.18, direction = "right"},
        {time = 11.50, direction = "right"},
        {time = 11.86, direction = "left"},
        {time = 12.19, direction = "left"},
        {time = 12.51, direction = "left"},
        {time = 12.81, direction = "left"},
        {time = 13.15, direction = "right"},
        {time = 13.50, direction = "right"},
        {time = 13.81, direction = "right"},
        {time = 14.09, direction = "right"},
        {time = 14.42, direction = "left"},
        {time = 14.74, direction = "left"},
        {time = 15.05, direction = "left"},
        {time = 15.37, direction = "left"},
        {time = 15.94, direction = "down"},

        -- 16-24 seconds
        -- Basic Pattern
        {time = 16.23, direction = "up"},
        {time = 16.50, direction = "down"},
        {time = 16.78, direction = "left"},
        {time = 17.05, direction = "right"},
        {time = 17.34, direction = "up"},
        {time = 17.64, direction = "down"},
        {time = 17.98, direction = "left"},
        {time = 18.26, direction = "right"}
    }
}