return {
    name = "Z Fighter's Anthem",
    audio = "assets/Z Fighter's Anthem.mp3",
    difficulty = "Custom",
    bpm = 120,
    arrows = {
        {time = 0.69, direction = "left"},
        {time = 0.94, direction = "right"},
        {time = 1.45, direction = "left"},
        {time = 1.70, direction = "right"},
        {time = 1.95, direction = "left"},
        {time = 2.20, direction = "right"},
        {time = 2.70, direction = "left"},
        {time = 2.95, direction = "right"},
        {time = 3.20, direction = "left"},
        {time = 3.45, direction = "right"},
        {time = 3.95, direction = "left"},
        {time = 4.20, direction = "right"},
        {time = 4.45, direction = "left"},
        {time = 4.70, direction = "right"},
        {time = 5.21, direction = "up"},
        {time = 5.46, direction = "down"},
        {time = 5.96, direction = "left"},
        {time = 6.21, direction = "right"},
        {time = 6.46, direction = "up"},
        {time = 6.96, direction = "down"},
        {time = 7.21, direction = "up"},
        {time = 7.46, direction = "down"},
        {time = 7.71, direction = "left"},
        {time = 7.96, direction = "right"},

        -- 8-16 seconds
        -- Intense Pattern
        {time = 8.46, direction = "up"},
        {time = 8.72, direction = "down"},
        {time = 8.97, direction = "left"},
        {time = 9.22, direction = "right"},
        {time = 9.72, direction = "left"},
        {time = 9.97, direction = "right"},
        {time = 10.22, direction = "up"},
        {time = 10.72, direction = "down"},
        {time = 11.22, direction = "left"},
        {time = 11.47, direction = "up"},
        {time = 11.72, direction = "down"},
        {time = 11.97, direction = "right"},
        {time = 12.22, direction = "up"},
        {time = 12.73, direction = "left"},
        {time = 12.98, direction = "right"},
        {time = 13.23, direction = "down"},
        {time = 13.73, direction = "up"},
        {time = 13.98, direction = "left"},
        {time = 14.23, direction = "right"},
        {time = 14.48, direction = "up"},
        {time = 14.98, direction = "down"},
        {time = 15.23, direction = "left"},
        {time = 15.48, direction = "right"},
        {time = 15.73, direction = "down"},

        -- 16-24 seconds
        -- Intense Pattern
        {time = 16.24, direction = "left"},
        {time = 16.49, direction = "up"},
        {time = 16.74, direction = "left"},
        {time = 17.24, direction = "right"},
        {time = 17.49, direction = "down"},
        {time = 17.74, direction = "up"},
        {time = 18.24, direction = "left"},
        {time = 18.49, direction = "right"},
        {time = 18.74, direction = "down"},
        {time = 19.24, direction = "up"},
        {time = 19.49, direction = "left"},
        {time = 19.74, direction = "right"},
        {time = 20.00, direction = "down"},
        {time = 20.50, direction = "left"},
        {time = 20.75, direction = "up"},
        {time = 21.00, direction = "down"},
        {time = 21.25, direction = "left"},
        {time = 21.75, direction = "right"},
        {time = 22.01, direction = "up"},
        {time = 22.26, direction = "down"},
        {time = 22.76, direction = "left"},
        {time = 23.01, direction = "right"},
        {time = 23.26, direction = "down"},
        {time = 23.76, direction = "up"},

        -- 24-32 seconds
        -- Intense Pattern
        {time = 24.01, direction = "left"},
        {time = 24.26, direction = "right"},
        {time = 24.76, direction = "down"},
        {time = 25.01, direction = "up"},
        {time = 25.26, direction = "left"},
        {time = 25.52, direction = "right"},
        {time = 26.02, direction = "down"},
        {time = 26.27, direction = "left"},
        {time = 26.52, direction = "up"},
        {time = 26.77, direction = "down"},
        {time = 27.02, direction = "left"},
        {time = 27.27, direction = "up"},
        {time = 27.52, direction = "right"},
        {time = 27.77, direction = "right"},
        {time = 28.02, direction = "down"},
        {time = 28.27, direction = "left"},
        {time = 28.52, direction = "up"},
        {time = 28.77, direction = "right"},
        {time = 29.02, direction = "down"},
        {time = 29.28, direction = "left"},
        {time = 29.53, direction = "up"},
        {time = 29.78, direction = "right"},
        {time = 30.03, direction = "down"},
        {time = 30.28, direction = "left"},
        {time = 30.53, direction = "down"},
        {time = 30.78, direction = "down"},
        {time = 31.03, direction = "up"},
        {time = 31.28, direction = "left"},
        {time = 31.28, direction = "right"},
        {time = 31.53, direction = "down"},
        {time = 31.78, direction = "down"},

        -- 32-40 seconds
        -- Intense Pattern
        {time = 32.03, direction = "left"},
        {time = 32.28, direction = "left"},
        {time = 32.53, direction = "right"},
        {time = 32.78, direction = "right"},
        {time = 33.04, direction = "right"},
        {time = 33.29, direction = "left"},
        {time = 33.54, direction = "up"},
        {time = 33.79, direction = "down"},
        {time = 34.04, direction = "left"},
        {time = 34.29, direction = "right"},
        {time = 34.79, direction = "right"},
        {time = 35.04, direction = "left"},
        {time = 35.29, direction = "down"},
        {time = 35.54, direction = "up"},
        {time = 35.79, direction = "left"},
        {time = 35.79, direction = "down"},
        {time = 36.04, direction = "right"},
        {time = 36.54, direction = "right"},
        {time = 36.54, direction = "left"},
        {time = 36.80, direction = "left"},
        {time = 36.80, direction = "right"},
        {time = 37.05, direction = "right"},
        {time = 37.30, direction = "down"},
        {time = 37.55, direction = "up"},
        {time = 37.80, direction = "left"},
        {time = 38.05, direction = "right"},
        {time = 38.30, direction = "right"},
        {time = 38.30, direction = "left"},
        {time = 38.55, direction = "right"},
        {time = 39.05, direction = "down"},
        {time = 39.05, direction = "left"},
        {time = 39.30, direction = "down"},
        {time = 39.30, direction = "left"},
        {time = 39.56, direction = "up"},
        {time = 39.80, direction = "right"},

        -- 40-48 seconds
        -- Intense Pattern
        {time = 40.06, direction = "down"},
        {time = 40.31, direction = "left"},
        {time = 40.56, direction = "right"},
        {time = 40.81, direction = "up"},
        {time = 41.06, direction = "left"},
        {time = 41.31, direction = "down"},
        {time = 41.31, direction = "right"},
        {time = 41.81, direction = "up"},
        {time = 42.06, direction = "down"},
        {time = 42.06, direction = "left"},
        {time = 42.31, direction = "right"},
        {time = 42.31, direction = "left"},
        {time = 42.56, direction = "right"},
        {time = 42.56, direction = "down"},
        {time = 42.82, direction = "left"},
        {time = 43.07, direction = "up"},
        {time = 43.32, direction = "up"},
        {time = 43.57, direction = "up"},
        {time = 43.57, direction = "left"},
        {time = 43.57, direction = "down"},
        {time = 43.57, direction = "up"},
        {time = 44.07, direction = "right"},
        {time = 44.32, direction = "down"},
        {time = 44.57, direction = "left"},
        {time = 44.82, direction = "down"},
        {time = 45.07, direction = "left"},
        {time = 45.07, direction = "up"},
        {time = 45.32, direction = "right"},
        {time = 45.57, direction = "down"},
        {time = 45.57, direction = "left"},
        {time = 45.82, direction = "up"},
        {time = 46.83, direction = "up"},
        {time = 46.83, direction = "left"},
        {time = 47.33, direction = "down"},
        {time = 47.33, direction = "right"},
        {time = 47.58, direction = "up"},
        {time = 47.83, direction = "left"},

        -- 48-56 seconds
        -- Intense Pattern
        {time = 48.08, direction = "up"},
        {time = 48.08, direction = "down"},
        {time = 48.33, direction = "left"},
        {time = 48.58, direction = "up"},
        {time = 48.83, direction = "right"},
        {time = 49.08, direction = "down"},
        {time = 49.08, direction = "left"},
        {time = 49.33, direction = "right"},
        {time = 49.58, direction = "up"},
        {time = 49.83, direction = "left"},
        {time = 50.09, direction = "down"},
        {time = 50.09, direction = "right"},
        {time = 50.34, direction = "up"},
        {time = 50.84, direction = "left"},
        {time = 50.84, direction = "up"},
        {time = 51.09, direction = "down"},
        {time = 51.09, direction = "left"},
        {time = 51.34, direction = "up"},
        {time = 51.59, direction = "right"},
        {time = 51.84, direction = "down"},
        {time = 51.84, direction = "left"},
        {time = 52.09, direction = "right"},
        {time = 52.34, direction = "down"},
        {time = 52.59, direction = "left"},
        {time = 52.84, direction = "right"},
        {time = 53.34, direction = "down"},
        {time = 53.60, direction = "left"},
        {time = 53.85, direction = "down"},
        {time = 54.10, direction = "right"},
        {time = 54.35, direction = "down"},
        {time = 54.60, direction = "up"},
        {time = 54.85, direction = "left"},
        {time = 55.10, direction = "right"},
        {time = 55.60, direction = "down"},
        {time = 55.85, direction = "left"},

        -- 56-64 seconds
        -- Intense Pattern
        {time = 56.35, direction = "right"},
        {time = 56.60, direction = "down"},
        {time = 57.11, direction = "left"},
        {time = 57.36, direction = "right"},
        {time = 57.86, direction = "right"},
        {time = 58.11, direction = "right"},
        {time = 58.36, direction = "down"},
        {time = 58.61, direction = "left"},
        {time = 59.11, direction = "down"},
        {time = 59.36, direction = "right"},
        {time = 59.61, direction = "right"},
        {time = 59.86, direction = "down"},
        {time = 60.11, direction = "left"},
        {time = 60.36, direction = "up"},
        {time = 60.61, direction = "right"},
        {time = 61.12, direction = "down"},
        {time = 61.37, direction = "left"},
        {time = 61.62, direction = "right"},
        {time = 61.87, direction = "left"},
        {time = 62.37, direction = "left"},
        {time = 62.62, direction = "right"},
        {time = 62.87, direction = "up"},
        {time = 63.12, direction = "left"},
        {time = 63.63, direction = "right"},
        {time = 63.88, direction = "right"},

        -- 64-72 seconds
        -- Intense Pattern
        {time = 64.13, direction = "left"},
        {time = 64.64, direction = "left"},
        {time = 64.89, direction = "right"},
        {time = 65.14, direction = "right"},
        {time = 65.39, direction = "left"},
        {time = 65.90, direction = "right"},
        {time = 66.16, direction = "left"},
        {time = 66.41, direction = "right"},
        {time = 66.91, direction = "left"},
        {time = 67.16, direction = "right"},
        {time = 67.41, direction = "up"},
        {time = 67.91, direction = "down"},
        {time = 68.16, direction = "left"},
        {time = 68.41, direction = "right"},
        {time = 68.66, direction = "left"},
        {time = 69.17, direction = "right"},
        {time = 69.42, direction = "left"},
        {time = 69.67, direction = "right"},
        {time = 70.17, direction = "down"},
        {time = 70.42, direction = "left"},
        {time = 70.67, direction = "right"},
        {time = 70.92, direction = "up"},
        {time = 71.42, direction = "left"},
        {time = 71.67, direction = "right"},
        {time = 71.92, direction = "left"},

        -- 72-80 seconds
        -- Intense Pattern
        {time = 72.17, direction = "right"},
        {time = 72.69, direction = "left"},
        {time = 72.94, direction = "left"},
        {time = 73.44, direction = "left"},
        {time = 73.69, direction = "left"},
        {time = 73.94, direction = "right"},
        {time = 74.19, direction = "right"},
        {time = 74.69, direction = "right"},
        {time = 74.94, direction = "left"},
        {time = 75.19, direction = "right"},
        {time = 75.69, direction = "left"},
        {time = 75.94, direction = "right"},
        {time = 76.19, direction = "left"},
        {time = 76.44, direction = "right"},
        {time = 76.95, direction = "left"},
        {time = 77.20, direction = "right"},
        {time = 77.45, direction = "right"},
        {time = 77.70, direction = "left"},
        {time = 78.21, direction = "right"},
        {time = 78.46, direction = "left"},
        {time = 78.72, direction = "right"},
        {time = 79.22, direction = "left"},
        {time = 79.47, direction = "right"},
        {time = 79.72, direction = "left"},
        {time = 79.97, direction = "right"},

        -- 80-88 seconds
        -- Intense Pattern
        {time = 80.47, direction = "left"},
        {time = 80.73, direction = "right"},
        {time = 80.98, direction = "up"},
        {time = 81.48, direction = "down"},
        {time = 81.73, direction = "left"},
        {time = 81.98, direction = "right"},
        {time = 82.48, direction = "left"},
        {time = 82.73, direction = "right"},
        {time = 82.98, direction = "right"},
        {time = 83.48, direction = "down"},
        {time = 83.73, direction = "left"},
        {time = 83.98, direction = "up"},
        {time = 84.24, direction = "down"},
        {time = 84.74, direction = "left"},
        {time = 84.99, direction = "right"},
        {time = 85.24, direction = "up"},
        {time = 85.49, direction = "down"},
        {time = 86.25, direction = "right"},
        {time = 86.50, direction = "left"},
        {time = 87.00, direction = "up"},
        {time = 87.25, direction = "down"},
        {time = 87.50, direction = "left"},

        -- 88-96 seconds
        -- Intense Pattern
        {time = 88.01, direction = "right"},
        {time = 88.26, direction = "left"},
        {time = 88.52, direction = "right"},
        {time = 88.77, direction = "down"},
        {time = 89.27, direction = "left"},
        {time = 89.52, direction = "right"},
        {time = 89.77, direction = "up"},
        {time = 90.27, direction = "left"},
        {time = 90.52, direction = "right"},
        {time = 90.77, direction = "left"},
        {time = 91.02, direction = "right"},
        {time = 91.52, direction = "up"},
        {time = 91.77, direction = "down"},
        {time = 92.02, direction = "left"},
        {time = 92.53, direction = "right"},
        {time = 92.78, direction = "right"},
        {time = 93.03, direction = "down"},
        {time = 93.28, direction = "left"},
        {time = 93.78, direction = "up"},
        {time = 94.03, direction = "right"},
        {time = 94.28, direction = "down"},
        {time = 94.78, direction = "left"},
        {time = 95.03, direction = "right"},
        {time = 95.28, direction = "left"},
        {time = 95.53, direction = "right"},

        -- 96-104 seconds
        -- Intense Pattern
        {time = 96.04, direction = "down"},
        {time = 96.30, direction = "left"},
        {time = 96.55, direction = "right"},
        {time = 97.05, direction = "down"},
        {time = 97.30, direction = "left"},
        {time = 97.55, direction = "right"},
        {time = 97.80, direction = "left"},
        {time = 98.31, direction = "right"},
        {time = 98.56, direction = "up"},
        {time = 98.81, direction = "down"},
        {time = 99.31, direction = "left"},
        {time = 99.57, direction = "right"},
        {time = 99.82, direction = "left"},
        {time = 100.07, direction = "right"},
        {time = 100.58, direction = "left"},
        {time = 100.83, direction = "right"},
        {time = 101.08, direction = "left"},
        {time = 101.58, direction = "right"},
        {time = 101.83, direction = "right"},
        {time = 102.08, direction = "left"},
        {time = 102.33, direction = "right"},
        {time = 102.85, direction = "up"},
        {time = 103.10, direction = "down"},
        {time = 103.35, direction = "left"},
        {time = 103.60, direction = "right"},

        -- 104-112 seconds
        -- Intense Pattern
        {time = 104.10, direction = "left"},
        {time = 104.61, direction = "right"},
        {time = 104.86, direction = "right"},
        {time = 105.61, direction = "right"},
        {time = 105.86, direction = "left"},
        {time = 106.36, direction = "right"},
        {time = 106.61, direction = "left"},
        {time = 106.86, direction = "right"},
        {time = 107.38, direction = "left"},
        {time = 107.63, direction = "right"},
        {time = 107.89, direction = "right"},
        {time = 108.14, direction = "up"},
        {time = 108.39, direction = "left"},
        {time = 108.64, direction = "right"},
        {time = 108.89, direction = "left"},
        {time = 109.39, direction = "right"},
        {time = 109.64, direction = "left"},
        {time = 109.89, direction = "right"},
        {time = 110.39, direction = "left"},
        {time = 110.64, direction = "right"},
        {time = 110.89, direction = "left"},
        {time = 111.14, direction = "right"},
        {time = 111.67, direction = "up"},
        {time = 111.92, direction = "down"},

        -- 112-120 seconds
        -- Intense Pattern
        {time = 112.17, direction = "left"},
        {time = 112.42, direction = "right"},
        {time = 112.92, direction = "down"},
        {time = 113.17, direction = "left"},
        {time = 113.42, direction = "right"},
        {time = 113.67, direction = "left"},
        {time = 114.17, direction = "right"},
        {time = 114.68, direction = "left"},
        {time = 115.18, direction = "right"},
        {time = 115.43, direction = "left"},
        {time = 115.68, direction = "up"},
        {time = 116.18, direction = "down"},
        {time = 116.43, direction = "left"},
        {time = 116.68, direction = "right"},
        {time = 117.18, direction = "left"},
        {time = 117.43, direction = "right"},
        {time = 117.68, direction = "left"},
        {time = 117.93, direction = "right"},
        {time = 118.44, direction = "left"},
        {time = 118.69, direction = "right"},
        {time = 118.94, direction = "left"},
        {time = 119.44, direction = "right"},
        {time = 119.69, direction = "left"},
        {time = 119.94, direction = "right"},

        -- 120-128 seconds
        -- Intense Pattern
        {time = 120.44, direction = "left"},
        {time = 120.69, direction = "right"},
        {time = 120.94, direction = "left"},
        {time = 121.20, direction = "right"},
        {time = 121.70, direction = "left"},
        {time = 121.95, direction = "right"},
        {time = 122.45, direction = "left"},
        {time = 122.70, direction = "right"},
        {time = 122.95, direction = "left"},
        {time = 123.20, direction = "right"},
        {time = 123.45, direction = "left"},
        {time = 123.95, direction = "left"},
        {time = 124.20, direction = "right"},
        {time = 124.45, direction = "up"},
        {time = 124.71, direction = "down"},
        {time = 125.21, direction = "left"},
        {time = 125.46, direction = "right"},
        {time = 125.71, direction = "left"},
        {time = 126.23, direction = "right"},
        {time = 126.23, direction = "left"},
        {time = 126.48, direction = "left"},
        {time = 126.73, direction = "right"},
        {time = 127.24, direction = "right"},
        {time = 127.49, direction = "left"},
        {time = 127.74, direction = "right"},
        {time = 127.99, direction = "left"},

        -- 128-136 seconds
        -- Intense Pattern
        {time = 128.50, direction = "right"},
        {time = 128.75, direction = "left"},
        {time = 129.00, direction = "right"},
        {time = 129.50, direction = "right"},
        {time = 129.75, direction = "right"},
        {time = 131.51, direction = "right"},
        {time = 131.76, direction = "left"},
        {time = 132.01, direction = "right"},
        {time = 132.26, direction = "left"},
        {time = 132.51, direction = "right"},
        {time = 132.76, direction = "left"},
        {time = 133.03, direction = "right"},
        {time = 133.53, direction = "right"},
        {time = 133.78, direction = "left"},
        {time = 134.28, direction = "right"},
        {time = 134.53, direction = "left"},
        {time = 135.03, direction = "right"}
    }
}